# Generated by Django 5.1.3 on 2024-11-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partes_de_Cima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=100)),
                ('cor', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('tamanho', models.CharField(choices=[('pp', 'PP'), ('p', 'P'), ('m', 'M'), ('g', 'G'), ('gg', 'GG'), ('xgg', 'XGG')], max_length=10)),
            ],
        ),
    ]
