# Generated by Django 5.1.3 on 2024-11-29 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partes_de_cima',
            options={'verbose_name': 'Parte de Cima', 'verbose_name_plural': 'Partes de Cima'},
        ),
    ]
