# Generated by Django 5.1.3 on 2024-11-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_lab', '0002_alter_partes_de_cima_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acessórios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=100)),
                ('cor', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('bolsa', 'Bolsa'), ('oculos', 'Óculos'), ('brinco', 'Brinco'), ('colares', 'Colares'), ('pulseira', 'Pulseira'), ('anel', 'Anel')], max_length=50)),
                ('tamanho', models.CharField(blank=True, choices=[('pequeno', 'Pequeno'), ('medio', 'Médio'), ('grande', 'Grande')], max_length=50, null=True)),
                ('material_acessorio', models.CharField(choices=[('couro', 'Couro'), ('tela', 'Tela'), ('plástico', 'Plástico'), ('metal', 'Metal'), ('pedras_preciosas', 'Pedras preciosas'), ('sintético', 'Sintético')], max_length=100)),
            ],
            options={
                'verbose_name': 'Acessório',
                'verbose_name_plural': 'Acessórios',
            },
        ),
        migrations.CreateModel(
            name='Calçados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=100)),
                ('cor', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('tamanho', models.IntegerField(choices=[(33, '33'), (34, '34'), (35, '35'), (36, '36'), (37, '37'), (38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45'), (46, '46')])),
                ('tipo', models.CharField(choices=[('esportivo', 'Esportivo'), ('social', 'Social'), ('botas', 'Botas'), ('sandália', 'Sandália'), ('rasteirinha', 'Rasteirinha'), ('sapatilha', 'Sapatilha')], max_length=50)),
                ('material_sola', models.CharField(blank=True, choices=[('borracha', 'Borracha'), ('couro', 'Couro'), ('plástico', 'Plástico'), ('sintético', 'Sintético')], max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Calçado',
                'verbose_name_plural': 'Calçados',
            },
        ),
        migrations.CreateModel(
            name='Partes_de_Baixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=100)),
                ('cor', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('tamanho', models.CharField(choices=[('pp', 'PP (36-38)'), ('p', 'P (38-40)'), ('m', 'M (40-42)'), ('g', 'G (42-44)'), ('gg', 'GG (44-46)'), ('xgg', 'XGG (46-48)'), ('extra_gg', 'Extra GG (48+)')], max_length=10)),
                ('comprimento', models.CharField(choices=[('curto', 'Curto'), ('médio', 'Médio'), ('longo', 'Longo')], max_length=10)),
            ],
            options={
                'verbose_name': 'Parte de Baixo',
                'verbose_name_plural': 'Partes de Baixo',
            },
        ),
        migrations.AlterField(
            model_name='partes_de_cima',
            name='tamanho',
            field=models.CharField(choices=[('pp', 'PP (36-38)'), ('p', 'P (38-40)'), ('m', 'M (40-42)'), ('g', 'G (42-44)'), ('gg', 'GG (44-46)'), ('xgg', 'XGG (46-48)'), ('extra_gg', 'Extra GG (48+)')], max_length=10),
        ),
    ]
