# Generated by Django 5.1.3 on 2024-11-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_lab', '0003_acessórios_calçados_partes_de_baixo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessórios',
            name='tipo',
            field=models.CharField(choices=[('bolsa', 'Bolsa'), ('oculos', 'Óculos'), ('brinco', 'Brinco'), ('colares', 'Colar'), ('pulseira', 'Pulseira'), ('anel', 'Anel')], max_length=50),
        ),
    ]
