# Generated by Django 5.1.3 on 2024-11-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_lab', '0004_alter_acessórios_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calçados',
            name='material_sola',
        ),
        migrations.AlterField(
            model_name='calçados',
            name='material',
            field=models.CharField(blank=True, choices=[('borracha', 'Borracha'), ('couro', 'Couro'), ('plástico', 'Plástico'), ('sintético', 'Sintético')], max_length=100, null=True),
        ),
    ]
