# Generated by Django 5.1.3 on 2024-11-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_lab', '0005_remove_calçados_material_sola_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessórios',
            name='cor',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='calçados',
            name='cor',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='partes_de_baixo',
            name='cor',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='partes_de_cima',
            name='cor',
            field=models.CharField(max_length=20),
        ),
    ]
