# Generated by Django 5.1.3 on 2024-12-04 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_lab', '0006_alter_acessórios_cor_alter_calçados_cor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='partes_de_cima',
            name='tamanho',
            field=models.CharField(choices=[('pp', 'PP'), ('p', 'P'), ('m', 'M'), ('g', 'G'), ('gg', 'GG'), ('xgg', 'XGG'), ('extra_gg', 'Extra GG')], max_length=10),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('feminino', 'Feminino'), ('masculino', 'Masculino'), ('nao-binario', 'Não-binário'), ('outro', 'Outro')], max_length=50)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
