# Generated by Django 5.1.3 on 2024-12-05 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_lab', '0007_alter_partes_de_cima_tamanho_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acessórios',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/acessorios/'),
        ),
        migrations.AddField(
            model_name='acessórios',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calçados',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/calcados/'),
        ),
        migrations.AddField(
            model_name='calçados',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partes_de_baixo',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/partes_de_baixo/'),
        ),
        migrations.AddField(
            model_name='partes_de_baixo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partes_de_cima',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/partes_de_cima/'),
        ),
        migrations.AddField(
            model_name='partes_de_cima',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
