# Generated by Django 5.1.3 on 2024-12-06 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_lab', '0009_alter_acessórios_usuario_alter_calçados_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessórios',
            name='imagem',
            field=models.ImageField(default='IMG/logo.png', upload_to='imagens/acessorios/'),
        ),
        migrations.AlterField(
            model_name='acessórios',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calçados',
            name='imagem',
            field=models.ImageField(default='IMG/logo.png', upload_to='imagens/calcados/'),
        ),
        migrations.AlterField(
            model_name='calçados',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partes_de_baixo',
            name='imagem',
            field=models.ImageField(default='IMG/logo.png', upload_to='imagens/partes_de_baixo/'),
        ),
        migrations.AlterField(
            model_name='partes_de_baixo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partes_de_cima',
            name='imagem',
            field=models.ImageField(default='IMG/logo.png', upload_to='imagens/partes_de_cima/'),
        ),
        migrations.AlterField(
            model_name='partes_de_cima',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
