# Generated by Django 5.1.3 on 2024-12-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_lab', '0010_alter_acessórios_imagem_alter_acessórios_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessórios',
            name='imagem',
            field=models.ImageField(upload_to='imagens/acessorios/'),
        ),
        migrations.AlterField(
            model_name='calçados',
            name='imagem',
            field=models.ImageField(upload_to='imagens/calcados/'),
        ),
        migrations.AlterField(
            model_name='partes_de_baixo',
            name='imagem',
            field=models.ImageField(upload_to='imagens/partes_de_baixo/'),
        ),
        migrations.AlterField(
            model_name='partes_de_cima',
            name='imagem',
            field=models.ImageField(upload_to='imagens/partes_de_cima/'),
        ),
    ]
