# Generated by Django 5.1.3 on 2024-12-06 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_lab', '0011_alter_acessórios_imagem_alter_calçados_imagem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acessórios',
            name='material',
        ),
    ]
