# Generated by Django 5.1.3 on 2024-12-11 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('fashion_lab', '0012_remove_acessórios_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsoRoupa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roupa_object_id', models.PositiveIntegerField()),
                ('data_uso', models.DateField()),
                ('avaliacao', models.IntegerField(choices=[(0, '0 estrelas'), (1, '1 estrelas'), (2, '2 estrelas'), (3, '3 estrelas'), (4, '4 estrelas'), (5, '5 estrelas')])),
                ('ocasiao', models.CharField(choices=[('trabalho', 'Trabalho'), ('lazer', 'Lazer'), ('festa', 'Festa'), ('casual', 'Casual'), ('formal', 'Formal'), ('outro', 'Outro')], max_length=100)),
                ('roupa_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
