# Generated by Django 5.1.3 on 2024-12-11 14:00

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_lab', '0013_usoroupa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acessórios',
            old_name='cor',
            new_name='cor_texto',
        ),
        migrations.RenameField(
            model_name='calçados',
            old_name='cor',
            new_name='cor_texto',
        ),
        migrations.RenameField(
            model_name='partes_de_baixo',
            old_name='cor',
            new_name='cor_texto',
        ),
        migrations.RenameField(
            model_name='partes_de_cima',
            old_name='cor',
            new_name='cor_texto',
        ),
        migrations.AddField(
            model_name='acessórios',
            name='cor_visual',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='calçados',
            name='cor_visual',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='partes_de_baixo',
            name='cor_visual',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='partes_de_cima',
            name='cor_visual',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
    ]
