# Generated by Django 5.1.3 on 2024-12-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_lab', '0014_rename_cor_acessórios_cor_texto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessórios',
            name='cor_visual',
            field=models.CharField(default='#FF0000', max_length=7),
        ),
        migrations.AlterField(
            model_name='calçados',
            name='cor_visual',
            field=models.CharField(default='#FF0000', max_length=7),
        ),
        migrations.AlterField(
            model_name='partes_de_baixo',
            name='cor_visual',
            field=models.CharField(default='#FF0000', max_length=7),
        ),
        migrations.AlterField(
            model_name='partes_de_cima',
            name='cor_visual',
            field=models.CharField(default='#FF0000', max_length=7),
        ),
    ]
