# Generated by Django 5.1.3 on 2024-12-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_lab', '0015_alter_acessórios_cor_visual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessórios',
            name='cor_visual',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='calçados',
            name='cor_visual',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='partes_de_baixo',
            name='cor_visual',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='partes_de_baixo',
            name='tamanho',
            field=models.CharField(choices=[('PP', 'PP (36-38)'), ('P', 'P (38-40)'), ('M', 'M (40-42)'), ('G', 'G (42-44)'), ('GG', 'GG (44-46)'), ('XGG', 'XGG (46-48)'), ('Extra GG', 'Extra GG (48+)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='partes_de_cima',
            name='cor_visual',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='partes_de_cima',
            name='tamanho',
            field=models.CharField(choices=[('PP', 'PP'), ('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('XGG', 'XGG')], max_length=10),
        ),
    ]
