# Generated by Django 5.1.3 on 2024-12-11 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('fashion_lab', '0016_alter_acessórios_cor_visual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usoroupa',
            name='ocasiao',
            field=models.CharField(choices=[('Trabalho', 'Trabalho'), ('Lazer', 'Lazer'), ('Festa', 'Festa'), ('Casual', 'Casual'), ('Formal', 'Formal'), ('Outro', 'Outro')], max_length=100),
        ),
        migrations.AlterField(
            model_name='usoroupa',
            name='roupa_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='contenttypes.contenttype'),
        ),
    ]
